---
- hosts: example
  tasks:
    - name: test echo
      shell: echo "test11" 
    - name: copy file to dest
      copy:
        src: ${env.WORKSPACE}/target/trucks.war
        dest: /root/
        owner: root
